import { SessionProvider } from "next-auth/react";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "sonner";

import getSession from "@/lib/get-session";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getSession();

    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider>{children}</SessionProvider>
                <Toaster richColors />
            </body>
        </html>
    );
}
